name: Test

on: 
    pull_request:
      branches:
        - master

--jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '18'

        -name: Install dependencies
          run: npm install

        --name: Prisma Client Generate
          run: npm run db:generate

        -name: Run Build
          run: npm run build
